#
# makefile author: jerry 
# date modified: 12 oct 2017
# 
# makefile for machine learning proj1
#


test:
	python3 nearest-neighbor.py

dataset: Main.java
	javac $<
	java Main

clean: 
	-rm *.class 
	-rm *.txt
